indexes_dir_path: "./code/llamaIndex/database"
document_preprocessing:
  data_dir_path: "./data"
  indexes:
    - "test-ollama-based"
    - "ollama-based"
rag:
  default_index: "test-ollama-based"
  llm: "vicuna:13b"
  # llm: "lmsys/vicuna-13b-v1.3"