indexes_dir_path: "./code/llamaIndex/database"
cache: "./code/llamaIndex/.cache"
document_preprocessing:
  data_dir_path: "./data/tmp"
  # data_dir_path: "./data"
  index_pipelines:
    - "test"
    # - "gpt-4o-batch-all"
    # - "ollama-based"
rag:
  # default_index: "test-ollama-based"
  default_index: null
  # llm: "lmsys/vicuna-13b-v1.3"
  llm: "vicuna:13b"
  # llm: "gpt-4o"
  isReRank: True
  